name: Generate Snake Animation

on:
  # Corre automaticamente todos os dias às 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Permite que corras isto manualmente quando quiseres (na aba "Actions")
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # O teu username do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # A lista de inputs que a cobra vai ler
          inputs: .github/workflows/snake-inputs.svg
          
          # O ficheiro de saída (o que o teu README está a tentar mostrar)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
        env:
          # O token do GitHub para ler as tuas contribuições privadas (se quiseres)
          # Se não quiseres contribs privadas na cobra, podes apagar esta linha
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # O token para fazer "push" do ficheiro gerado
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
